// Design Tokens
export const tokens = {
  colors: {
    background: '#ffffff',
    secondary: '#AD6B14',
    primary: '#5F2D14',
    surface: '#f5f5f5',
    text: '#1a1a1a',
    textSecondary: '#666666',
    border: '#e0e0e0',
    error: '#ef4444',
    success: '#10b981',
    renoSand: '#AD6B14',
    ripeLemon: '#F8E22D',
    jambalaya: '#5F2D14',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  typography: {
    fontFamily: '"Italia Std", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSizeSmall: '12px',
    fontSizeBase: '14px',
    fontSizeLarge: '16px',
    fontSizeXL: '20px',
    fontSizeXXL: '24px',
    fontSizeH1: 'clamp(48px, 8vw, 96px)',
    fontSizeH2: 'clamp(20px, 3vw, 32px)',
    fontWeightNormal: '400',
    fontWeightMedium: '500',
    fontWeightBold: '700',
    fontWeightExtraBold: '800',
    lineHeightTight: '1.2',
    lineHeightNormal: '1.5',
    lineHeightRelaxed: '1.75',
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    full: '9999px',
    clamped: 'clamp(4px, 0.5em, 12px)',
    button: 'clamp(8px, 1em, 16px)',
  },
  borders: {
    width: '2px',
    style: 'solid',
    default: '2px solid transparent',
  },
  shadows: {
    sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px rgba(0, 0, 0, 0.1)',
    lg: '0 10px 15px rgba(0, 0, 0, 0.1)',
  },
  transitions: {
    fast: '150ms',
    base: '200ms',
    slow: '300ms',
  },
  gradients: {
    primary: 'linear-gradient(135deg, #00c4cc, #7d2ae8)',
  },
} as const;

export type Tokens = typeof tokens;
